version: '2'
services:
  app:
    build: .
    environment:
      NODE_ENV: docker
    command: node_modules/.bin/nodemon --exec npm start
    ports:
      - '3000:3000'
    tty: true
    depends_on:
      - mongodb
    volumes:
      - .:/home/app/node_docker
      - /home/app/node_docker/node_modules
  mongodb:
    image: mongo:3.2.5
    ports:
      - '27017:27017'
